### PR TITLE
Add GraphQL support for sitemaps

### PR DESCRIPTION
**Pull request by aerni**
This PR adds GraphQL support for sitemaps.

A basic query looks like this:

```graphql
query MyQuery {
  seoSitemap {
    alternates {
      href
      hreflang
    }
    changefreq
    lastmod
    loc
    priority
  }
}
```

You can also filter by `site`:

```graphql
query MyQuery {
  seoSitemap(site: "default") {
    loc
  }
}
```

It's also possible to filter by `type` and `handle`. Possible values for `type` are `collection`, `taxonomy`, and `custom`.

```graphql
query MyQuery {
  seoSitemap(type: "collection", handle: "pages") {
    loc
  }
}
```

You may also change the `baseUrl` like this:

```graphql
query MyQuery {
  seoSitemap(baseUrl: "https://foo.bar") {
    loc
  }
}
```

### CODE REVIEW

**Comment by maartenvanhunsel** [comment]
@aerni approved, looking good.
@el-schneider you can add your `frontend_url` by the code below in sites.php.
```
 'sites' => [
        'default' => [
            'name' => config('app.name'),
            'locale' => 'nl_NL',
            'url' => env('FRONTEND_URL', '/'),
        ],
    ],
```

**Comment by aerni** [comment]
@maartenvanhunsel Awesome! Thanks for taking the time.
@el-schneider Can you confirm that adding the frontend URL to the sites config does what you need?

**Comment by el-schneider** [comment]
Not really, because this also affects asset urls and a plugin I'm using to generate srcsets. But it's fine. I'll just transform the urls myself.

**Comment by aerni** [comment]
Oh ok. Will look into adding `base_url`.

**Comment by maartenvanhunsel** [comment]
@aerni tested and works like expected. Would you mind to merge :D

**Comment by aerni** [comment]
Thanks for testing! After looking at it again, I think I might want to separate the collection, taxonomy, and custom sitemaps and structure the query similarly to how the `seoDefaults` query is structured. 

It would look like this:

```graphql
query MyQuery {
  seoSitemap {
    collection(handle: "pages") {
      loc
    }
    taxonomy(handle: "tags") {
      loc
    }
    custom {
      loc
    }
  }
}
```

This way, we could get rid of the `type` argument. And it's always clear which type of sitemap URLs you get. Also, it would more closely resemble the way Advanced SEO's XML sitemaps are structured.

**Pull request merged**
