### PR TITLE
GraphQL Support

### PR DESCRIPTION
**Pull request by aerni**
This PR adds support for GraphQL and closes https://github.com/aerni/statamic-advanced-seo/issues/23. It provides multiple queries and types to get all the SEO data you can think of.

## TODO
- [x] #38 
- [x] Refactor cascade to make it work with GraphQL
- [x] Test SEO defaults fields
- [x] Test SEO entry and term fields
- [x] Test all conditional fields (social images generator, sitemap)
- [x] Add `og_image_size` and `twitter_image_size` fields
- [x] Make a decision about type and query structure

## SEO Type

The easiest way to get the SEO data of your entries and terms is to use the newly added `seo` type on the existing `entries`, `entry`, `terms`, and `term` queries. The `seo` type consists of three distinct subtypes. The best way to explore all the fields is to use Statamic's GraphQL explorer in the Control Panel.

**Subtypes:**
| Type               | Description   |
| ------------- | ------------- |
| computed | Computed fields like the `title`, `hreflang`, or `indexing` |
| raw | The unprocessed SEO fields from the entry or term  |
| views | The rendered Advanced SEO `head` and `body` views |

**Example:** 
```graphql
{
  entry {
    seo {
      computed {
        title
      }
      raw {
        description
      }
      views {
        body
      }
    }
  }
}
```

## SEO Meta Query

Use the `seoMeta` query to get the SEO meta data of an entry or term by its `id`.

```graphql
{
  seoMeta(id: "1d366a68-855e-4145-81ea-87174826a4eb") {
    computed {
      title
    }
  }
}
```

Use the optional `site` parameter to get the data in the provided site.

```graphql
{
  seoMeta(id: "tags::brands", site: "german") {
    computed {
      title
    }
  }
}
```

## SEO Defaults Query

Use the `seoDefaults` query to get the site, collections, and taxonomy defaults.

### Site Defaults

Use the `site` field to get the site defaults.

```graphql
{
  seoDefaults {
    site {
      general {
        site_name
      }
    }
  }
}
```

Use the optional `site` parameter to get the data in the provided site.

```graphql
{
  seoDefaults {
    site(site: "german") {
      general {
        site_name
      }
    }
  }
}
```

### Collection Defaults

Use the `collections` field to get the defaults of a collection by its `handle`.

```graphql
{
  seoDefaults {
    collections(handle: "pages") {
      title
    }
  }
}
```

Use the optional `site` parameter to get the data in the provided site.

```graphql
{
  seoDefaults {
    collections(handle: "pages", site: "german") {
      title
    }
  }
}
```

### Taxonomy Defaults

Use the `taxonomies` field to get the defaults of a taxonomy by its `handle`.

```graphql
{
  seoDefaults {
    taxonomies(handle: "tags") {
      title
    }
  }
}
```

Use the optional `site` parameter to get the data in the provided site.

```graphql
{
  seoDefaults {
    taxonomies(handle: "tags", site: "german") {
      title
    }
  }
}
```

### CODE REVIEW

**Comment by Narretz** [comment]
Since I'm evaluating Advanced SEO + graphql with an existing statamic site, I was wondering if it is "normal" that you first have to save all collection / taxonomies once to get values for the seo_fields. For example, the standard for `meta title` is `@auto` to inherit the value from the `title` field, but unless you save the entry, you get `null` in graphql for `seo_title`. 

On the other hand, the standard for `Meta description` is to inherit the value from the collection default, and if you query seo_description with graphql, you *do* get the default value, even though in the yml for the entry you don't have `seo_description: '@default'`.

So my question is if it's possible to get the field inheritance for `meta title` without having to add `seo_title: '@auto'` to all entries first.

**Comment by aerni** [comment]
@Narretz I just released a fix for this. If a field has a default value of `@auto` or `@default`, but the field is `null` on the entry/term, it will now fall back correctly.

Also, if you're installing the addon into an existing site, I recommend running the [Migrator](https://github.com/aerni/statamic-advanced-seo#migration) to save all addon-related values to your entries and terms.

**Comment by aerni** [comment]
This PR opened a whole can of worms. 

Advanced SEO is built around features and conditional blueprints. The Social Images Generator, for instance, can be enabled for individual collections. All fields associated with the generator would then only be included in the blueprint if the collection was selected. This mechanism isn't compatible with GraphQL, resulting in all dynamic blueprint fields being hidden from GraphQL. 

I'm already working on a solution that moves this dynamic blueprint logic from PHP to JS. This would ensure that all fields are always included in the blueprint and only visually hidden/visible in the UI. So far, so good.

I've now run into a roadblock with conditional fields that I outlined here: https://github.com/statamic/ideas/issues/856.

**Comment by Narretz** [comment]
Hm, the progress seemed too good to be true :)

I left a comment in the ticket with a possible workaround.

**Comment by aerni** [comment]
Your workaround seems to work fine for now. Thanks!

**Comment by aerni** [comment]
I created PR #38 that refactors the conditional fields. There's still some work to do before I can continue with the GraphQL integration.

**Comment by aerni** [comment]
@Narretz I just merged the conditional fields refactor. This should make the way to finishing the GraphQL implementation. Feel free to test and report back.

**Comment by aerni** [comment]
@Narretz I stumbled upon a conceptual question that I'd like your thoughts about. I've never worked with a headless application and need some input to make the API as straightforward as possible.

So far, you can get any entry's seo fields like so:

```graphql
{
  entries {
    data {
      seo {
        seo_title
        seo_description
      }
    }
  }
}
```

Now, this addon provides some cascade magic when working with Antlers. One example is the meta title. The cascade takes the entry's `seo_title` and merges it with a title separator and site name to finally output something like `Home / My Website`. The cascade also includes other fields like the `site_name` or `site_json_ld`. It essentially includes all the fields that are needed in the `<head>` tag.

My question is where this cascade should be available to you. Should it be a separate field in the entries query? Something like this:

```graphql
{
  entries {
    data {
      seo_cascade {
        title
        description
      }
    }
  }
}
```

Or should the cascade be its own query? Something like this:

```graphql
{
  seoCascade(id: "entry-id") {
    title
  }
}
```

Do you have any thoughts on this?

**Comment by aerni** [comment]
Another thought I had was to simplify everything and instead simply provide a `head` and `body` field, which would return the rendered HTML view similar to the Antlers tags. This would make the implementation on my side so much easier. And probably also for the consumer of the API, as you don't have to worry about your view logic anymore. It's all taken care of.

```graphql
{
  entries {
    data {
      seo {
        head
        body
      }
    }
  }
}
```

**Comment by Narretz** [comment]
Hi @aerni, thanks for getting me into the loop. 

For the cascade, I think a separate query type makes more sense, as at least in my case with headless CMS, the client often does a lot of data merging and customizing itself (for example if you have multiple data sources)

For that reason, it's also impractical if the output is html, unfortunately.

**Comment by el-schneider** [comment]
Hi @aerni. It's quite the opposite for me. In most cases I'd prefer a field attached to the Entry, so I don't have to do any merging. HTML output would work well with Svelte's `<svelte:head>` tag, but probably not as well with Nuxt, as it requires you to fill objects with your metadata (https://nuxtjs.org/docs/features/meta-tags-seo/) or React (https://github.com/reactjs/rfcs/pull/129). So admittedly it won't be useful for many people, but at least for me it would.

**Comment by aerni** [comment]
> For the cascade, I think a separate query type makes more sense, as at least in my case with headless CMS, the client often does a lot of data merging and customizing itself (for example if you have multiple data sources)

@Narretz Can you explain a little more? How is a separate `seoCascade` query better than a `seo_cascade` field within the `entries` and `terms` query? The cascade can only be built from an entry or term. So from my point of view, it makes more sense to have a field within the existing `entries` and `terms` query. Let's say you want to get all the data for your pages. You now only have to perform one query. If it were a separate `seoCascade` query, you'd have to perform two queries to get all the data for your pages.

That being said, I think it's pretty easy to supply both the `seo_cascade` field and `seoCascade` query.

Again, I never worked with GraphQL. So any advice about the best approach is very much appreciated.

**Comment by aerni** [comment]
> Hi @aerni. It's quite the opposite for me. In most cases I'd prefer a field attached to the Entry, so I don't have to do any merging. HTML output would work well with Svelte's `<svelte:head>` tag, but probably not as well with Nuxt, as it requires you to fill objects with your metadata (https://nuxtjs.org/docs/features/meta-tags-seo/) or React ([reactjs/rfcs#129](https://github.com/reactjs/rfcs/pull/129)). So admittedly it won't be useful for many people, but at least for me it would.

@el-schneider Thanks for the explanation and those links. That helps me understand things a lot more.

**Comment by Narretz** [comment]
@aerni I find it conceptually easier to separate the "normal" data and the "cascade" if the cascade is a separate query, but if it's in the same query as the entry that's also no problem at all.

**Comment by aerni** [comment]
@Narretz @el-schneider I'm very close to finishing this PR. Do you mind giving this a try? I'm open to any feedback you might have concerning the structure and naming of the fields. I've updated the description of this PR to document how to use it.

**Comment by aerni** [comment]
I have another question for you. Is it ok for the addon to return absolute URLs based on the config of the Laravel app? Or should it return relative URLs because the frontend might be hosted on a different domain?

Take the `hreflang` as an example:

```json
{
  "data": {
    "entry": {
      "seo": {
        "computedData": {
          "hreflang": [
            {
              "url": "https://statamic-advanced-seo.test"
            },
            {
              "url": "https://statamic-advanced-seo.test/de"
            },
            {
              "url": "https://statamic-advanced-seo.test/fr"
            }
          ]
        }
      }
    }
  }
}
```

**Comment by Narretz** [comment]
I think it should be relative. In my case the app is on a different domain.

**Comment by aerni** [comment]
> I think it should be relative. In my case, the app is on a different domain.

That's what I thought. I separated the URL into two fields, similar to how Statamic handles this. A `url` field for the relative URL and a `permalink` field for the absolute URL.

There are a couple of other fields, like the `breadcrumbs` and `schema,` that are not as straightforward, though. Let's take the `schema` as an example. How would you deal with this field on your frontend? Would you parse the JSON and prepend all the relative URLs with your app's base URL? Is that the way you would handle this? 

```json
{
  "data": {
    "entry": {
      "seo": {
        "computedData": {
          "schema": "{\"@context\":\"https:\\/\\/schema.org\",\"@type\":\"Person\",\"name\":\"Michael Aerni\",\"url\":\"\\/\"}"
        }
      }
    }
  }
}
```

Or maybe I could add a parameter to the `schema` field, which lets you pass your app's URL and automatically prepend it to all the returned URLs.

```graphql
schema(appUrl: "https://statamic.dev")
```

How would you deal with this situation?

**Comment by aerni** [comment]
Closing this PR in favor of #45.

**Pull request closed without merging**
